version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  pre_build:
    commands:
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain thecomein --domain-owner 091340909384 --region ap-southeast-1 --query authorizationToken --output text`
      - rm src/script/mvn/settings.xml
      - cp src/script/mvn/settings.xml ~/.m2/settings.xml
      - echo Test started on `date`
      - mvn clean compile test
  build:
    commands:
      - echo Build started on `date`
      - mvn package
      - mv target/centaurs-1.0.1-0-aws.jar .
      - unzip centaurs-1.0.1-0-aws.jar
      - rm -rf target tst src buildspec.yml pom.xml centaurs-1.0.1-0-aws.jar
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
  post_build:
    commands:
      # Do not remove this statement. This command is required for AWS CodeStar projects.
      # Update the AWS Partition, AWS Region, account ID and project ID in the project ARN on template-configuration.json file so AWS CloudFormation can tag project resources.
      - sed -i.bak 's/\$PARTITION\$/'${PARTITION}'/g;s/\$AWS_REGION\$/'${AWS_REGION}'/g;s/\$ACCOUNT_ID\$/'${ACCOUNT_ID}'/g;s/\$PROJECT_ID\$/'${PROJECT_ID}'/g' template-configuration.json
artifacts:
  files:
    - template-export.yml
    - template-configuration.json
