AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members
  CodeDeployRole:
    Type: String
    Description: IAM role to allow AWS CodeDeploy to manage deployment of AWS Lambda functions
  Stage:
    Type: String
    Description: The name for a project pipeline stage, such as Staging or Prod, for which resources are provisioned and deployed.
    Default: ''
  ComeInDBHost:
    Type: String
    Description: db host
    Default: 'artemis.cluster-csl5nc2u4rsg.ap-northeast-1.rds.amazonaws.com'
  ComeInDBPort:
    Type: String
    Description: db port
    Default: '5432'
  ComeInDBUsername:
    Type: String
    Description: db username
    Default: 'postgres'
  ComeInDBPassword:
    Type: String
    Description: db password
    Default: 'Dg8HtJjwEJDugpqTx5dR'
  ComeInDBInstance:
    Type: String
    Description: db instance
    Default: 'comein'
  ComeInCognitoUserPoolId:
    Type: String
    Description: The name for a project pipeline stage, such as Staging or Prod, for which resources are provisioned and deployed.
    Default: 'ap-southeast-1_sH5GQOfGD'
  ComeInCognitoRegion:
    Type: String
    Description: The name for a project pipeline stage, such as Staging or Prod, for which resources are provisioned and deployed.
    Default: 'ap-southeast-1'
  ComeInResponseTemplate:
    Type: String
    Description: response-template
    Default: $input.json('$.json-body')
  ComeInRequestTemplate:
    Type: String
    Description: request-template
    Default: |
      #set($allParams = $input.params())
      {
      "body" : "$util.escapeJavaScript($input.body)",
      "json-body" : $input.json('$'),
      "path" : "$context.resourcePath",
      "profile":{
         "email" : "$context.authorizer.claims.email",
         "comein-id":"$context.authorizer.claims['custom:comein_id']",
         "ref-name" : "$context.authorizer.claims.name",
         "sub":"$context.authorizer.claims.sub"   
        }, 
      #set($header_params = $allParams.get('header'))
      "headers" : {
         "spring.cloud.function.definition" : "${SpringFuncName}"
          #if(!$header_params.isEmpty),#end
          #foreach($paramName in $header_params.keySet())
          "$paramName" : "$util.escapeJavaScript($header_params.get($paramName))"
              #if($foreach.hasNext),#end
          #end
      },
      #set($path_params = $allParams.get('path'))
      "path-parameters" : {
          #foreach($paramName in $path_params.keySet())
          "$paramName" : "$util.escapeJavaScript($path_params.get($paramName))"
              #if($foreach.hasNext),#end
          #end
      },
      #set($query_params = $allParams.get('querystring'))
      "query-string-parameters" : {
          #foreach($paramName in $query_params.keySet())
          "$paramName" : "$util.escapeJavaScript($query_params.get($paramName))"
              #if($foreach.hasNext),#end
          #end
      },
      "stage-variables" : {
      #foreach($key in $stageVariables.keySet())
      "$key" : "$util.escapeJavaScript($stageVariables.get($key))"
          #if($foreach.hasNext),#end
      #end
      },
      "request-context" : {
          "account-id" : "$context.identity.accountId",
          "api-id" : "$context.apiId",
          "api-key" : "$context.identity.apiKey",
          "authorizer-principal-id" : "$context.authorizer.principalId",
          "caller" : "$context.identity.caller",
          "cognito-authentication-provider" : "$context.identity.cognitoAuthenticationProvider",
          "cognito-authentication-type" : "$context.identity.cognitoAuthenticationType",
          "cognito-identity-id" : "$context.identity.cognitoIdentityId",
          "cognito-identity-pool-id" : "$context.identity.cognitoIdentityPoolId",
          "http-method" : "$context.httpMethod",
          "stage" : "$context.stage",
          "source-ip" : "$context.identity.sourceIp",
          "user" : "$context.identity.user",
          "user-agent" : "$context.identity.userAgent",
          "user-arn" : "$context.identity.userArn",
          "request-id" : "$context.requestId",
          "resource-id" : "$context.resourceId",
          "resource-path" : "$context.resourcePath"
          }
      }
          
Globals:
  Function:
    AutoPublishAlias: live
    DeploymentPreference:
      Enabled: true
      Type: Canary10Percent5Minutes
      Role: !Ref CodeDeployRole

Resources:

  ComeInRestApi:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      # Body:
        # OpenAPI specification: null
      Description: Centaurs ComeIn API
      Name: MyCentaursAPI
      
  ComeInAuthorizer:
    Type: 'AWS::ApiGateway::Authorizer'
    Properties:  
      Name: comein_authorizer
      Type: COGNITO_USER_POOLS
      RestApiId: !Ref ComeInRestApi
      IdentitySource: method.request.header.comein_auth
      ProviderARNs: 
        - !Sub arn:aws:cognito-idp:${ComeInCognitoRegion}:${AWS::AccountId}:userpool/${ComeInCognitoUserPoolId}
      
  MyCentaursFunc:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'awscodestar-${ProjectId}-lambda-MyCentaursFunc'
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      Environment:
        Variables:
          DB_HOST: !Ref ComeInDBHost
          DB_PORT: !Ref ComeInDBPort
          DB_INSTANCE: !Ref ComeInDBInstance
          DB_USERNAME: !Ref ComeInDBUsername
          DB_PASSWORD: !Ref ComeInDBPassword
      Runtime: java11
      Timeout: 30
      MemorySize: 512
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
        
# Start API Function - GetHelloWorld 
  GetHelloWorldPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref MyCentaursFunc
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ComeInRestApi}/*/POST/hello-world

  GetHelloWorldResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref ComeInRestApi
      ParentId: !GetAtt 
        - ComeInRestApi
        - RootResourceId
      PathPart: hello-world

  GetHelloWorldMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ComeInRestApi
      ResourceId: !Ref GetHelloWorldResource
      HttpMethod: POST
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref ComeInAuthorizer
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        Uri:  !Join ['', ['arn:aws:apigateway:', !Ref AWS::Region, ':lambda:path/2015-03-31/functions/', !GetAtt MyCentaursFunc.Arn, '/invocations']]
        PassthroughBehavior: WHEN_NO_TEMPLATES
        RequestTemplates: 
#          'application/json': !Ref ComeInRequestTemplate
           'application/json': !Sub 
             - !Ref ComeInRequestTemplate
             - SpringFuncName: "getHelloWorld"
        IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates:
              'application/json' : !Ref ComeInResponseTemplate
      MethodResponses:
        - StatusCode: 200     
# End API Function - GetHelloWorld 


  LambdaExecutionRole:
    Description: Creating service role in IAM for AWS Lambda
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'CodeStar-${ProjectId}-Execution${Stage}'
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [lambda.amazonaws.com]
          Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      PermissionsBoundary: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/CodeStar_${ProjectId}_PermissionsBoundary'
